# Generated by Django 4.2.9 on 2026-03-29 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_points', models.IntegerField(default=0)),
                ('all_time_points', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_active', models.DateField(auto_now_add=True)),
                ('week_reset_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_marks', models.IntegerField(default=0)),
                ('starting_level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], max_length=20)),
                ('current_level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], max_length=20)),
                ('subject_status', models.CharField(choices=[('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default='IN_PROGRESS', max_length=20)),
                ('beginner_done', models.BooleanField(default=False)),
                ('intermediate_done', models.BooleanField(default=False)),
                ('advanced_done', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
