# Generated by Django 4.2.9 on 2026-03-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AddField(
            model_name='material',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
